### ISSUE TITLE
Error running GridGameExample.java

### ISSUE THREAD

**Issue by alinakhay** [jmacglashan/burlap_examples#1]
Hello, I have the following error, when running GridGameExample.java:

Exception in thread "main" java.lang.NullPointerException
	at burlap.behavior.stochasticgames.solvers.MinMaxSolver.getColPlayersStrategy(MinMaxSolver.java:60)
	at burlap.behavior.stochasticgames.solvers.MinMaxSolver.getRowPlayersStrategy(MinMaxSolver.java:25)
	at burlap.behavior.stochasticgames.madynamicprogramming.backupOperators.CoCoQ.performBackup(CoCoQ.java:63)
	at burlap.behavior.stochasticgames.agents.maql.MultiAgentQLearning.observeOutcome(MultiAgentQLearning.java:269)
	at burlap.mdp.stochasticgames.world.World.runStage(World.java:441)
	at burlap.mdp.stochasticgames.world.World.runGame(World.java:338)
	at burlap.mdp.stochasticgames.world.World.runGame(World.java:306)
	at burlap.mdp.stochasticgames.world.World.runGame(World.java:296)
	at edu.brown.cs.burlap.examples.GridGameExample.QLCoCoTest(GridGameExample.java:163)
	at edu.brown.cs.burlap.examples.GridGameExample.main(GridGameExample.java:235)

Can you please suggest possible error source and how to fix it? Thanks

**Comment by IngyN** [comment]
I have the same error with all the methods except saInterface example. It seems to be a problem with the iniatilization of the solver from scpsolve. Any ideas how to fix it?

EDIT: 
I figured out a way to make it work. I used JDK 7 for 32-bit instead of 64
[https://stackoverflow.com/questions/28394041/scpsolver-with-java-nullpointerexception-a-runnable-example](https://stackoverflow.com/questions/28394041/scpsolver-with-java-nullpointerexception-a-runnable-example)
